# frozen_string_literal: true

name             'rb-manager'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures redborder manager'
version          '5.22.0'

depends 'rb-common'
depends 'chef-server'
depends 'zookeeper'
depends 'kafka'
depends 'druid'
depends 'http2k'
depends 'memcached'
depends 'consul'
depends 'nginx'
depends 'geoip'
depends 'snmp'
depends 'rbmonitor'
depends 'rbscanner'
depends 'webui'
depends 'f2k'
depends 'pmacct'
depends 'logstash'
depends 'postgresql'
depends 'yara'
depends 'minio'
depends 'aerospike'
depends 'rbdswatcher'
depends 'rbevents-counter'
depends 'rsyslog'
depends 'rbnmsp'
depends 'rbale'
depends 'n2klocd'
depends 'freeradius'
depends 'rbcep'
depends 'rb-selinux'
depends 'rbaioutliers'
depends 'rbcgroup'
depends 'rblogstatter'
depends 'rb-arubacentral'
depends 'rb-postfix'
depends 'rb-clamav'
depends 'rb-chrony'
depends 'keepalived'
depends 'mem2incident'
depends 'rb-firewall'
depends 'rb-druid-indexer'
depends 'secor'
depends 'redis'
depends 'rb-agents'
depends 'airflow'
depends 'rb-reputation'
